version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:  
      - "5433:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - ./redis/data:/data

  nestjs:
    build:
      context: .
      dockerfile: .dockerfile
    container_name: nestjs
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src/:/app/src/